### ISSUE TITLE
Get json data from only required properties based on the attributes set

### ISSUE THREAD

**Issue by Kishan-Shiva** [json-everything/json-everything#749]
### Documentation

- [X] I have consulted the [documentation](https://docs.json-everything.net), and my question isn't answered there.

### Nuget Package

JsonSchema.Net

### Package Version

6.0.7

### How can I help?  Please provide as much context as possible.

I have a class which has few attributes set for each property. I would like to have JSON data as the output which needs to contain only those values for which [JsonExclude] and [Const(true)] attributes are not set.

```c#
public class GetJsonData
{
    public GetJsonData()
    {
        Name = "XYZ";
        Address = "XYZ";
        Mobile = "1234567890";
    }
    [Required]
    public string Name
    { get; set; }

    [JsonExclude]
    public string NameAlias
    { get; set; }

    [Required]
    public string Address
    { get; set; }

    [Required]
    public string Mobile
    { get; set; }

    [Const(true)]
    public string AlternativeNUmber
    { get; set; }
}
```

I create an object on the above class and I need to show the data to be as below:

```json
{
    "Name": "XYZ,"
    "Address": "XYZ",
    "Mobile": 1234567890,
}
```

Please let me know how can I achieve this?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
I'm not sure what you're asking here.  You've tagged _JsonSchema.Net_ but it looks like you want to generate data (which would be _JsonSchema.Net.DataGeneration_).

However, it also looks like you want to generate data _from a class_, which isn't something any of my libraries do.

- _JsonSchema.Net_ validates JSON data against schemas.
- _JsonSchema.Net.Generation_ generates schemas from classes.
- _JsonSchema.Net.DataGeneration_ generates data from schemas.

Can you clarify your question a bit, please?

**Comment by Kishan-Shiva** [comment]
@gregsdennis: Thanks for your reply. What I am looking at is that I need remove some properties from a C# object during serialization using the attributes set to each property. For example, in the above example, GetJsonData class, attributes [JsonExclude] and [Const(true)] should not get serialized and I am looking at the final serialized data as below:

{
    "Name": "XYZ,"
    "Address": "XYZ",
    "Mobile": 1234567890,
}

**Comment by gregsdennis** [comment]
Okay, but how are JSON Schema or the libraries offered by this repository used in what you're asking?

These libraries don't affect serialization.

**Comment by gregsdennis** [comment]
@Kishan-Shiva I'm happy to help with your question, I'm just trying to figure out if you're having a problem with my libraries or with something else.

**Comment by Kishan-Shiva** [comment]
@gregsdennis : Thanks for your help and support. I was able to resolve the issue using https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/customize-properties?pivots=dotnet-6-0. This issue can be closed.
Thanks again.
