### ISSUE TITLE
EvaluationResults default value shows up in Annotations when number out or range, but not on other situations

### ISSUE THREAD

**Issue by leonardo-gooten** [json-everything/json-everything#758]
### Nuget Package

JsonSchema.Net

### Package Version

7.1.1

### Operating System

Windows

### .Net Target (if relevant, please specify the version in the description)

.Net (5 or after)

### A clear and concise description of the bug.

This is the schema 

```json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Person",
    "type": "object",
    "properties": {
        "firstName": {
            "type": "string",
            "description": "The person's first name.",
            "default": "Capt Kathryn"
        },
        "lastName": {
            "type": "string",
            "description": "The person's last name.",
            "default": "Janeway"
        },
        "age": {
            "description": "Age in years which must be equal to or greater than zero.",
            "type": "integer",
            "minimum": 15,
            "default": 36
        }
    },
    "required": ["firstName"]
}
```

When age is less than minimum, EvaluationResults will have an entity more or less like this 

```json
{
    "valid": false,
    "evaluationPath": "/properties/age",
    "schemaLocation": "https://json-everything.net/758f688bd2#/properties/age",
    "instanceLocation": "/age",
    "errors": {
        "minimum": "14 should be at least 15"
    }
}
```

with a Annotations!["default"]!.GetValue<int>() == 36.
     
So the default value shows up in the Validation report. But for other kinds of erros, default value doesn't show up.. like required fields missing,.

### What did you expect?

I image that default value should shows up in any validation or none at all

### Please add test code or steps to reproduce the behavior.

schema
```json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Person",
    "type": "object",
    "properties": {
        "firstName": {
            "type": "string",
            "description": "The person's first name.",
            "default": "Capt Kathryn"
        },
        "lastName": {
            "type": "string",
            "description": "The person's last name.",
            "default": "Janeway"
        },
        "age": {
            "description": "Age in years which must be equal to or greater than zero.",
            "type": "integer",
            "minimum": 15,
            "default": 36
        }
    },
    "required": ["firstName"]
}
```

Json for test, with missing firstName

```json
{
    "lastName": "no last name",
    "age": 16
}
```

### Code of Conduct & Contributor Guidelines

- [X] I agree to follow this project's Code of Conduct and Contribution Guidelines.

**Comment by gregsdennis** [comment]
This is by design.

When validation fails for a subschema, any annotations that would have been collected by that subschema are dropped.

This library holds them in the output data structure but doesn't include them when serialized.

**Comment by gregsdennis** [comment]
@leonardo-gooten does this answer your question?

**Comment by leonardo-gooten** [comment]
Yes. thank you.
