### ISSUE TITLE
Pattern and PatternProperties keyword performance and security improvements

### ISSUE THREAD

**Issue by rikbosch** [json-everything/json-everything#761]
### Nuget Package

JsonSchema.Net

### Package Version

7.1.4

### Can this library make doing something simpler?

The PatternKeyword and the PatternPropertiesKeyword implementations both create new compiled `Regex`  instances.

According to best practices as described here: https://learn.microsoft.com/en-us/dotnet/standard/base-types/best-practices-regex#static-regular-expressions regex instances that are often used should be cached for performance benefits.

To achieve this, the keywords could use the static `Regex.IsMatch` method to use the internal cache (optionally add an entry in the `readme`  file to increase the [Regex.CacheSize](https://learn.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regex.cachesize?view=net-8.0) property.

Another options is to implement a regex cache within the JsonSchema.net library.

Also, `Regex` instances [should set a timeout](https://learn.microsoft.com/en-us/dotnet/standard/base-types/best-practices-regex#use-time-out-values) especially because json schema's will validate untrusted user input.

I'd be happy to create a PR for this, but that would require breaking changes to the `PatternKeyword` and the `PatternPropertiesKeyword` I think. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
> regex instances that are often used should be cached for performance benefits

I'm not sure how the current implementation doesn't handle this.

The current implementation stores the regex, compiled, within the keyword instance where it's used.  It only parses and compiles the regex once: upon creation (whether from deserialization or the schema builder).

Contrast this to the example in the docs you linked, which builds a new regex object every time the method is called.  I agree that this is bad practice.

**Comment by rikbosch** [comment]
It might be related to our usecase where we have a lot of different jsonschema's, but where the same patterns are used often. In that case, using the global regex cache would cache on a higher level then the `JsonSchema` instance (or keyword for that matter), improving performance overall.

**Comment by gregsdennis** [comment]
Sharing patterns across schemas is actually a really good use case.  I hadn't considered that. 

Please go ahead and create a PR.  Try to avoid breaking changes where you can.  If you can, obsolete existing API and create new.
