### ISSUE TITLE
How to add a keyword before another one

### ISSUE THREAD

**Issue by rikbosch** [json-everything/json-everything#762]
### Documentation

- [X] I have consulted the [documentation](https://docs.json-everything.net), and my question isn't answered there.

### Nuget Package

JsonSchema.Net

### Package Version

7.1.2

### How can I help?  Please provide as much context as possible.

We have a usecase where we first need to sanitize (clean) user input before evaluating the regex patterns and minlength / maxlength keywords

So we created a custom keyword and implemented the `Evaluator` method to replace the value:

```csharp
   private static void Evaluator(KeywordEvaluation evaluation, EvaluationContext context,
           SanitizerDelegate sanitizer)
   {
       // this is not really an evaluator but actually it's changes (sanitizes) the value of the incoming node
       var schemaValueType = evaluation.LocalInstance.GetSchemaValueType();
       if (schemaValueType is not SchemaValueType.String)
       {
           evaluation.MarkAsSkipped();
           return;
       }

       var str = evaluation.LocalInstance!.GetValue<string>();
       var sanitized = sanitizer(str);
       evaluation.LocalInstance.ReplaceWith(sanitized);
   }
```

Initially I thought I could use the `SchemaPriorityAttribute` and ensure this keyword is evaluated before the `PatternKeyword`, `MinLengthKeyword` and `MaxLengthKeyword`. But the`SchemaPriorityAttribute` was removed in version 5 in favor of the `DependsOnAnnotationsFromAttribute`.

Is there a way to insert a keyword before other keywords? Or is another solution preferred?
 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
The santization you're trying to do needs to be performed before schema evaluation.  JSON Schema absolutely should not modify the instance.

---

As far as getting a keyword to run _before_ another.... I don't think I have a solution for that.  `[DependsOnAnnotationsFrom]` instructs a keyword to run _after_ another.

What you could do is subclass `MinKeyword` and `MaxKeyword` and apply the attribute on the subclasses.  When you register the keywords, they'll override the default ones.  (You'll need to provide converters as well.)

**Comment by rikbosch** [comment]
I agree, the santizing has to be done before schema evaluation. However, in our case we're using json schema to first detect the used schema, to know what properties we need to sanitize.

We've implemented it in another way, only annotating the fields with the sanitizers that need to run for the field. Our system now first evaluates the jsonschema to detect sanitizers, apply the sanitizers and afterwards evaluate the schema again to see if sanitizing the values did not break the patterns or min/max length constraints.

Thanks for your input!
