### ISSUE TITLE
Schema validation doesn't fill EvaluationResults with any Errors for anyOf

### ISSUE THREAD

**Issue by armanossiloko** [json-everything/json-everything#763]
### Nuget Package

JsonSchema.Net

### Package Version

7.1.2

### Operating System

Windows

### .Net Target (if relevant, please specify the version in the description)

.Net (5 or after)

### A clear and concise description of the bug.

I have a use case where I generate a JSON schema for a type in the form of `anyOf` where `anyOf` can be either the given type or an array of the same type. Later on, that generated JSON schema is used for some validation where some JSON is validated with `JsonSchema.Evaluate()`. However, there is no errors ever filled for the "end user" to know what is wrong with their JSON data at all

### What did you expect?

From the test code that I provide, `result.IsValid` is set to `false`, which is good. However, the final `EvaluationResults` instance contains no date beside saying that it is invalid.

![image](https://github.com/json-everything/json-everything/assets/16511442/ee26e511-571d-4aa5-aebe-65ad69cf045f)

The expected behavior is that there's an error saying that the property `Name` was set to `null` when the schema did not allow for it.

### Please add test code or steps to reproduce the behavior.

```csharp
using Json.Schema;
using System.Text.Json.Nodes;

var jsonData = """
    [
        {
            "Name": null,
            "DisplayName": "My Display Name"
        }
    ]
    """;
var schemaJson = """
    {
      "anyOf": [
        {
          "type": "object",
          "properties": {
            "Name": {
              "type": "string"
            },
            "DisplayName": {
              "type": "string"
            }
          },
          "required": [
            "Name"
          ]
        },
        {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "Name": {
                "type": "string"
              },
              "DisplayName": {
                "type": "string"
              }
            },
            "required": [
              "Name"
            ]
          }
        }
      ]
    }
    """;

var schema = JsonSchema.FromText(schemaJson);
var result = schema.Evaluate(JsonNode.Parse(jsonData));
var errors = new List<string>();
if (!result.IsValid)
{
    if (result.HasErrors)
    {
        foreach ((string key, string value) in result.Errors ?? new Dictionary<string, string>())
        {
            errors.Add($"{key}: {value}");
        }
    }

}

Console.WriteLine(string.Join(", ", errors));
```

### Code of Conduct & Contributor Guidelines

- [X] I agree to follow this project's Code of Conduct and Contribution Guidelines.

**Comment by gregsdennis** [comment]
Please be sure you've read the [documentation](https://docs.json-everything.net/schema/basics/#schema-results).  It says the default output format is Flag, which only contains the boolean result.

Secondly, `allOf` doesn't produce an error; you'll need to look at errors from other keywords.

**Comment by armanossiloko** [comment]
@gregsdennis It's `anyOf` rather than `allOf`, but I suppose that would produce the same result. Passing options with `OutputFormat.List` doesn't produce any errors either, but I'll take a look tomorrow. Thanks for the reply.

**Comment by gregsdennis** [comment]
A great place to check the output is on https://json-everything.net.  That gives

```json
{
  "valid": false,
  "details": [
    {
      "valid": false,
      "evaluationPath": "",
      "schemaLocation": "https://json-everything.net/90b7b14ec1#",
      "instanceLocation": ""
    },
    {
      "valid": false,
      "evaluationPath": "/anyOf/0",
      "schemaLocation": "https://json-everything.net/90b7b14ec1#/anyOf/0",
      "instanceLocation": "",
      "errors": {
        "type": "Value is \"array\" but should be \"object\""
      }
    },
    {
      "valid": false,
      "evaluationPath": "/anyOf/1",
      "schemaLocation": "https://json-everything.net/90b7b14ec1#/anyOf/1",
      "instanceLocation": ""
    },
    {
      "valid": false,
      "evaluationPath": "/anyOf/1/items",
      "schemaLocation": "https://json-everything.net/90b7b14ec1#/anyOf/1/items",
      "instanceLocation": "/0"
    },
    {
      "valid": false,
      "evaluationPath": "/anyOf/1/items/properties/Name",
      "schemaLocation": "https://json-everything.net/90b7b14ec1#/anyOf/1/items/properties/Name",
      "instanceLocation": "/0/Name",
      "errors": {
        "type": "Value is \"null\" but should be \"string\""
      }
    },
    {
      "valid": true,
      "evaluationPath": "/anyOf/1/items/properties/DisplayName",
      "schemaLocation": "https://json-everything.net/90b7b14ec1#/anyOf/1/items/properties/DisplayName",
      "instanceLocation": "/0/DisplayName"
    }
  ]
}
```

The output unit you're interested in is

```json
{
  "valid": false,
  "evaluationPath": "/anyOf/1/items/properties/Name",
  "schemaLocation": "https://json-everything.net/90b7b14ec1#/anyOf/1/items/properties/Name",
  "instanceLocation": "/0/Name",
  "errors": {
    "type": "Value is \"null\" but should be \"string\""
  }
}
```

Since you're using an `anyOf`, it would also be a good idea to read through https://json-schema.org/blog/posts/interpreting-output.
