### ISSUE TITLE
Why is NullableAttribute needed for nullable properties

### ISSUE THREAD

**Issue by armanossiloko** [json-everything/json-everything#765]
### Documentation

- [X] I have consulted the [documentation](https://docs.json-everything.net), and my question isn't answered there.

### Nuget Package

JsonSchema.Net.Generation

### Package Version

4.3.0.2

### How can I help?  Please provide as much context as possible.

When I have a class with a nullable property (e.g `string? Whatever`), why is it required to specify the `[Json.Schema.Generation.Nullable(true)]` attribute on top of that property for the JSON schema to be properly generated? Shouldn't the fact that the property is nullable be enough for that?

Based on the class below

```csharp
public class MyClass
{
    [Json.Schema.Generation.Required]
    [Required]
    public int Id { get; set; }

    // Having this uncommented produces the expected result, but it doesn't make sense that we have to explicitly declare it as nullable; the property is already nullable.
    //[Json.Schema.Generation.Nullable(true)]
    public string? Name { get; set; }
}
```

I get this JSON Schema generated:

```json
{
  "type": "object",
  "properties": {
    "Id": {
      "type": "integer"
    },
    "Name": {
      "type": [
        "string"
      ]
    }
  },
  "required": [
    "Id"
  ]
}
```

And when trying to validate the following JSON through that schema, it doesn't work, because `Value is "null" but should be "string"` (or something along these lines)

```json
[
    {
        "Name": null,
        "Id": 1
    }
]
```

When adding the attribute `[Json.Schema.Generation.Nullable(true)]`, I get this schema instead (in which case the validation works):
```json
{
  "type": "object",
  "properties": {
    "Id": {
      "type": "integer"
    },
    "Name": {
      "type": [
        "string",
        "null"
      ]
    }
  },
  "required": [
    "Id"
  ]
}
```

So, my question is: why is is it required to apply that property to be able to have a nullable property in your JSON data? It feels obsolete to have a nullable property and then having to declare that this property will be nullable using some custom attribute.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
Please read the documentation.  I've explained the design decisions quite thoroughly there.

https://docs.json-everything.net/schema/schemagen/schema-generation/#schema-schemagen-nullability

**Comment by armanossiloko** [comment]
Doesn't really answer the question, but cheers.

**Comment by gregsdennis** [comment]
I'm happy to provide more clarity.  This has been asked multiple times, so obviously something is missing, but I don't know what it is.
