### ISSUE TITLE
Referencing Known Schema-Type Mappings during Schema Generation

### ISSUE THREAD

**Issue by luisjones** [json-everything/json-everything#768]
### Documentation

- [X] I have consulted the [documentation](https://docs.json-everything.net), and my question isn't answered there.

### Nuget Package

JsonSchema.Net.Generation

### Package Version

4.3.0.2

### How can I help?  Please provide as much context as possible.

I currently have logic in my common library where I generate Schemas as such:
```csharp
foreach (var schemaToGenerate in _options.SchemasToGenerate)
{
    var key = schemaToGenerate.Key;
    using StreamWriter sw = new StreamWriter($"Schemas/{key}.json");

    var schema = schemaBuilder
        .Title(key)
        .Id(key)
        .FromType(schemaToGenerate.Value, schemaGeneratorConfiguration)
        .Build();

     var schemaStr = JsonSerializer.Serialize(schema, jsonSerializerOptions);
     sw.Write(schemaStr); 
}
```
where both configs and options pass in a CamelCase naming convention.

In my service I then have

```csharp
services.AddSchemas(new Dictionary<string, Type>()
{ 
    { "TestNestedClass", typeof(TestNestedClass) },
    { "TestClass", typeof(TestClass) },
});
```
which references my class that contains a nested class:
```csharp
public class TestClass
{
    [Description("Test Name")]
    public string Name { get; set; }

    public TestNestedClass NestedClass { get; set; }
}

public class TestNestedClass
{
    [Description("An additional property")]
    public string AdditionalProperty { get; set; }
}
```

This successfully generates 2 schemas, TestClass.json and TestNestedClass.json.
The contents of my TestClass.json is
```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "TestClass",
  "$id": "TestClass",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "Test Name"
    },
    "nestedClass": {
      "type": "object",
      "properties": {
        "additionalProperty": {
          "type": "string",
          "description": "An additional property"
        }
      }
    }
  }
}
```

Ideally I would like my TestClass.json to have a $ref pointing to TestNestedClass.json. I have followed the external references example at https://docs.json-everything.net/schema/examples/external-schemas/ by attempting to add
```SchemaRegistry.Global.Register(schema);``` both during the iteration loop where the schemas are being written to files, and using the FromFile example, however with no success. How could I go about adding this $ref dynamically, so that my nestedClass points to the second schema file instead of internally?

Thanks

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
Hey there.  Thanks for the report.

The generator just looks at the requested type and the types that it contains and generates schemas for everything.

I do like the idea of letting the user explicitly specify a mapping between known schemas and the types they model, but that's not a thing right now.

I'm going to list this as an enhancement opportunity.

**Comment by luisjones** [comment]
Thanks for the reply!

**Comment by gregsdennis** [comment]
@luisjones I have a question of usability.

Currently in the PR above ☝️, I have the support set up as a simple mapping from a type to a URI.  While this works, I wonder if it will become cumbersome to set this up for every generation (or at least for every config).

What I'm thinking as an alternative is an `[Id]` attribute:

- If the class at the root has the attribute an `$id` keyword will be added to the generated schema.
- If the generation encounters a type with the attribute, a `$ref` keyword will be added instead of the type being generated.

I think this is probably a better approach, but I'd like a user's feedback.

**Comment by luisjones** [comment]
Oh wow thanks! I personally quite like that idea and think it would provide more flexibility. Thank you for maintaining this great library

**Comment by gregsdennis** [comment]
Of course. It's my baby! 😁

I was thinking about having implemented both now in the PR, and I think I might just keep both approaches. 

The attribute I think will be the "standard" way, but then the config allows supporting types that can't be modified.  Also, the config would provide a way to override the attribute if needed.

![c26959f6-e709-41d5-a811-9067af1688f4_text.gif](https://github.com/user-attachments/assets/ac5e12d3-896e-4a3e-95b8-f20aaf77d11b)

This is gonna be fun to document.
