### ISSUE TITLE
JSON Pointer release notes describe reverted breaking change from class to struct

### ISSUE THREAD

**Issue by amis92** [json-everything/json-everything#777]
### What's your idea or question?

#719 was a rewrite of the JSON Pointer. During that PR the Pointer was rewritten as struct, but then was again changed into a class.

Release notes for v5.0.0 of JSON Pointer were not amended and still say that the change happened and API changed.

Also, not really a doc issue, but PointerSegment is no longer used (there are three usages and only JsonPointer.Create is public) and could be removed for clarity.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
Yeah, it looks like I never changed that back.  I had initially made it a struct, but I wasn't getting the performance I was expecting, so I changed it back to an immutable class.  Thanks for pointing that out.

Regarding `PointerSegment`, it _is_ used, just not directly.  It's now basically just a proxy class that allows you to chain together strings and ints in the `.Create()` method.  It's quite important, so I can't remove it.
