### ISSUE TITLE
String formats are not being validated

### ISSUE THREAD

**Issue by CoreDumpSoftware** [json-everything/json-everything#779]
### Nuget Package

JsonSchema.Net

### Package Version

7.1.2

### Operating System

Windows

### .Net Target (if relevant, please specify the version in the description)

.Net (5 or after)

### A clear and concise description of the bug.

Validating data in JSON format against its schema is not enforcing `format` tags.

### What did you expect?

Validation should fail if a string is not matching the expected format.  I ran my schema and test data on the online JSON Schema validator (saved test here: https://www.jsonschemavalidator.net/s/rNQqUw8J) and the validator fails the data as expected. 

### Please add test code or steps to reproduce the behavior.

Running the following code in a basic console app does not cause

`var schemaJson = """
    {
        "type": "object",
        "properties": {
            "DateCreated": {
                "type": "string",
                "format": "date-time"
            }
        },
        "required": [
            "DateCreated"
        ]
    }
    """;

var schema = JsonSchema.FromText(schemaJson);

var dataJson = """
{
   "DateCreated": "Not a date",
   }
}
""";

var results = schema.Evaluate(JsonNode.Parse(dataJson), new EvaluationOptions
{
    OutputFormat = OutputFormat.List
});

var evalResult = JsonSerializer.Serialize(results, new JsonSerializerOptions
{
    WriteIndented = true
});

Console.WriteLine(evalResult);`

### Code of Conduct & Contributor Guidelines

- [X] I agree to follow this project's Code of Conduct and Contribution Guidelines.

**Comment by gregsdennis** [comment]
Hey thanks for the question.  Please read through the format validation section of the documentation. 

Per the specification, `format` does not validate by default.

https://docs.json-everything.net/schema/basics/#schema-format

**Comment by CoreDumpSoftware** [comment]
I apologize, I missed an option in the EvaluationOptions object that enabled format validation. I assumed it was something that would be enabled by default and hadn't noticed it previously.
