### ISSUE TITLE
Is there a way to manage $def's?

### ISSUE THREAD

**Issue by CoreDumpSoftware** [json-everything/json-everything#780]
### Documentation

- [X] I have consulted the [documentation](https://docs.json-everything.net), and my question isn't answered there.

### Nuget Package

json-everything.net (playground)

### Package Version

7.1.2

### How can I help?  Please provide as much context as possible.

I've got several fields which follow a particular decimal precision and scale format (think things like money, geocoordinates, and percents), I have learned how to make use of the IAttributeHandler interface to simplify defining these and it's helped greatly to simplify my schema definitions, but I was wondering if there is a way to control the name of the $def/$ref names that's generated? Currently it'll spit out things like "string1" or "number1" which is technically fine, but I'd like to be able to control the name if at all possible.

Thanks in advance!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
On `SchemaGenerationContextOptimizer`, there is a static `ITypeNameGenerator? TypeNameGenerator` property that you can use to do this.

**Comment by gregsdennis** [comment]
I just noticed that this is in regard to the placeground.  The above apply to the library.  I don't have a way to do this online.
