### ISSUE TITLE
3221225477 (0xc0000005) 'Access violation'. error while using GenerateData() function.

### ISSUE THREAD

**Issue by Grgpuran07** [json-everything/json-everything#783]
### Documentation

- [X] I have consulted the [documentation](https://docs.json-everything.net), and my question isn't answered there.

### Nuget Package

JsonSchema.Net.DataGeneration

### Package Version

2.2.2

### How can I help?  Please provide as much context as possible.

```c#
 var builder1 = new JsonSchemaBuilder()
 .Type(SchemaValueType.Object)
 .Properties(
     (nameof(TestMenu.Name), new JsonSchemaBuilder()
         .Type(SchemaValueType.String)
     ),
     (nameof(TestMenu.Children), new JsonSchemaBuilder()
         .Type(SchemaValueType.Array)
         .Items(new JsonSchemaBuilder().Ref("#"))
     )
 );

 var schema1 = builder1.Build();
 var result = schema1.GenerateData();
```

When i used above code it was working properly for

- JsonSchema.Net -> Version="2.1.1",
- JsonSchema.Net.Data -> Version="1.0.5",
- JsonSchema.Net.DataGeneration -> Version="0.1.1" 
- JsonSchema.Net.Generation -> Version="1.8.3"

these versions. When i updated all these packages to latest stable packages then same code is showing issue. It seems like due to infinite loop. Is there any alternatives please.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
When you say that this code was working properly for v2.1.1, what do you mean?  What was the result?

It's confusing that you claim this since `$ref` is not (and never has been) supported by data generation.

**Comment by Grgpuran07** [comment]
In older version:
var result = schema.GenerateData();
 var sampleData = result.Result;
Debug.Print("sampleData: {0}", JsonSerializer.Serialize(sampleData));

Output:
sampleData: {"Est":["commodi",-618420129535441279,null,"Nihil nobis beatae et.\nEst illo dolorem saepe dolorem doloremque.\nLaborum maxime quisquam ipsa.\nTempora facere nemo eos consequatur aliquam est reprehenderit.","Praesentium iure vero."],"tenetur":"Saepe consequatur molestiae laboriosam.","iste":-403483623559697510,"et":null,"magni":null}

**Comment by Grgpuran07** [comment]
Hello @gregsdennis,

I have added my result after generating data in lower version. How can I change code so that it works in newer version or should I follow another approach for implementing this. Please!
Thanks .

**Comment by gregsdennis** [comment]
By "works" I expect you mean "doesn't throw an exception".

`$ref` was partially supported with v2.1.0.  (You're coming from v0.1.1, which is quite a jump.)  The [release notes](https://docs.json-everything.net/rn-json-schema-datageneration/) for that version clearly state that `$ref` support doesn't include infinite recursion, which is a feature that your schema has (the `$ref: #`).

This scenario is not supported, and the release notes explicitly state that.  I don't expect it to be supported soon given my [reduced availability](https://blog.json-everything.net/posts/end-of-an-era/) for this project.
