### ISSUE TITLE
Trailing '.' on a JsonPath string in TryParse() causes an IndexOutOfRangeException

### ISSUE THREAD

**Issue by Nexiimil** [json-everything/json-everything#787]
### Nuget Package

json-everything.net (playground)

### Package Version

1.1.4

### Operating System

Windows

### .Net Target (if relevant, please specify the version in the description)

.Net (5 or after)

### A clear and concise description of the bug.

If I try to parse a JsonPath string, say "$." using TryParse(), it throws an IndexOutOfRangeException instead of returning false for a failed parse.

### What did you expect?

A false Boolean return, I think

### Please add test code or steps to reproduce the behavior.

TryParse("$.", out _);

### Code of Conduct & Contributor Guidelines

- [X] I agree to follow this project's Code of Conduct and Contribution Guidelines.

**Comment by gregsdennis** [comment]
Thanks.  I have a lot of hardening to do on the website.  The parse is supposed to throw when it finds an invalid path.

**Comment by Nexiimil** [comment]
Ah apologies for the confusion, I didn't mean to list the website specifically, I've imported the package to a project at work, and it seems to be throwing there.

**Comment by gregsdennis** [comment]
No worries. I figured it out. New package available.
