### ISSUE TITLE
Throws a PathParseException when source string contains $

### ISSUE THREAD

**Issue by mrt181** [json-everything/json-everything#793]
### Nuget Package

JsonPath.Net

### Package Version

1.1.5

### Operating System

Linux

### .Net Target (if relevant, please specify the version in the description)

.Net (5 or after)

### A clear and concise description of the bug.

When I try to create a `JsonPath` that contains a `$` I get a `PathParseException`.

### What did you expect?

The `JsonPath` object should be created and evaluate to this result when used with the test code.

```json
[
  "https://schemas/foo/v1#/$defs/foo",
  "https://schemas/bar/v1#/$defs/bar"
]
```

### Please add test code or steps to reproduce the behavior.

This is a sample json that uses `$ref' fields as specified in json-schema.
```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$defs": {
    "asset": {
      "type": "object",
      "properties": {
        "foo": {
          "$ref": "https://schemas/foo/v1#/$defs/foo"
        },
        "bar": {
          "$ref": "https://schemas/bar/v1#/$defs/bar"
        }
      }
    }
  }
}
```

And this is the code that tries to get the `$ref` values
```csharp
    var schemaNode = JsonNode.Parse(schema)!;
    var path = JsonPath.Parse("$..$ref");
    var eval = path.Evaluate(schemaNode).Matches.ToArray();
```

### Is there any other information you'd like to share regarding this bug?

I have tested the json-path from the code example here:
https://jsonpath.com/
https://jsonpath.curiousconcept.com/#

### Code of Conduct & Contributor Guidelines

- [X] I agree to follow this project's Code of Conduct and Contribution Guidelines.

**Comment by gregsdennis** [comment]
> `$..$ref`

This isn't a valid JSON Path: only alphanumeric chars (and underscore) may be used as shorthand name selector (the `$ref` part).  In order to select that name, you'll need to use the bracket syntax:

```jsonpath
$..['$ref']
```

**Comment by mrt181** [comment]
Thank you. Using the new syntax fixes the issue.
