### ISSUE TITLE
IsEquivalentTo FormatException for large double numbers

### ISSUE THREAD

**Issue by SGStino** [json-everything/json-everything#794]
### Nuget Package

Json.More.Net

### Package Version

2.0.2

### Operating System

None

### .Net Target (if relevant, please specify the version in the description)

.Net (5 or after)

### A clear and concise description of the bug.

```a.IsEquivalentTo(b)``` fails with FormatException if double value doesn't fit in decimal.

### What did you expect?

`true` or `false`

### Please add test code or steps to reproduce the behavior.

RoslynPad reproducable:
```csharp
#r "nuget: Json.More.Net, 2.0.2"

using System.Text.Json;
using Json.More;

var str = "{\"a\": 1.0332671e+36, \"b\":2.1292569e+29}";
var json = JsonSerializer.Deserialize<JsonElement>(str);

json.Dump();


var a = json.GetProperty("a");
var b = json.GetProperty("b");

a.IsEquivalentTo(b).Dump();
```

### Is there any other information you'd like to share regarding this bug?

I'm not entirely sure how one should go about comparing these values.. 
decimal, double, string comparison fallbacks via TryGet?

adding a dependency like https://github.com/tompazourek/Rationals might be overkill for this issue?

### Code of Conduct & Contributor Guidelines

- [X] I agree to follow this project's Code of Conduct and Contribution Guidelines.

**Comment by gregsdennis** [comment]
The [docs](https://docs.json-everything.net/schema/basics/) explicitly state that using `decimal` was a design decision.  (Yes, it's in the JSON Schema section.)  This entire suite follows this philosophy that precision in JSON is more important than range.  You can find a bit more on this in [this blog post](https://blog.json-everything.net/posts/numbers-are-numbers-not-strings/).

**Comment by gregsdennis** [comment]
I could be open to this, but I would want it across the suite, not just in JsonSchema.Net.  That means it would need to be Json.More.Net to be used everywhere.

I'd also want it `IConvertible` so that it can easily be converted to native numeric types.

> with the addition of NaN, +Inf, -Inf to cover the possibility of the "Inf", "NaN" formattings

This I don't agree with.  It should model JSON, not .Net's notion of JSON.  [These values are not numbers.](https://blog.json-everything.net/posts/numbers-are-numbers-not-strings/)

**Comment by SGStino** [comment]
Considering the issue i encountered was in Json.More.Net, not the Schemas, i'd imagine it needs to be that deeply integrated.

I'll start with prototyping that type so you can validate it, and then we can look where to implement it?

**Comment by gregsdennis** [comment]
Let's start there.  Introducing the type to that lib isn't a breaking change, but integrating it into the others will be.  That can be done later.

**Comment by SGStino** [comment]
exactly, this just extends on the idea to convert the string on-demand to the required precision. 
It's just that in this exact case, the demanded precision isn't known, and hidden inside the library's equality function with no way to extend or override it easily as developer.

If the comparison can use the full-precision type to do the equality check, that shouldn't break anything. (except for already broken cases?)

**Comment by SGStino** [comment]
> I'd also want it IConvertible so that it can easily be converted to native numeric types.

Isn't that slightly dangerous? Some internal marshal calls might think it's an actual native type with GetTypeCode() ..
Wouldn't TypeConverters and implicit or explicit operators be cleaner?
