### ISSUE TITLE
JsonIgnore/JsonExclude does not work on enum members

### ISSUE THREAD

**Issue by 2BitSalute** [json-everything/json-everything#795]
### Nuget Package

JsonSchema.Net.Generation

### Package Version

4.5.0

### Operating System

Windows

### .Net Target (if relevant, please specify the version in the description)

.Net (5 or after)

### A clear and concise description of the bug.

The `JsonIgnore`/`JsonExclude` attributes should apply to enum members, which doesn't seem to happen, currently.

### What did you expect?

When I tag an enum member with `[JsonIgnore]`, I expect it not to appear in the generated schema.

### Please add test code or steps to reproduce the behavior.

Suppose these are my types:

```
public enum Bar
{
    [JsonIgnore]
    Invalid,
    X,
    Y
}

public class Foo
{
    public Bar PropBar { get; set; }

    public string PropZ { get; set; } = "PropZDefault";

    [JsonIgnore]
    public string InvalidProp { get; set; } = "InvalidPropDefault";
}
```

I generate the schema based on them:

```
var schemaBuilder = new JsonSchemaBuilder();
var schema = schemaBuilder.FromType<Foo>().Build();
```

In the resulting schema, `InvalidProp` on `Foo` is ignored, as expected, but the `Invalid` member on `Bar` is not:

```
{
  "type": "object",
  "properties": {
    "PropBar": {
      "enum": [
        "Invalid",
        "X",
        "Y"
      ]
    },
    "PropZ": {
      "type": "string"
    }
  }
}
```

### Is there any other information you'd like to share regarding this bug?

It is common to have one enum member, such as like `None`, `Undefined`, etc. that indicates that the value is not set. This value should not be considered valid in the context where users are specifying something explicitly, such as in a schematized config file.

This issue would block me from using the package for generating the schema. I need to exclude the None values which are expected in the internal implementation using the enum but should not be suggested or accepted in configuration by the generated JSON schema.

### Code of Conduct & Contributor Guidelines

- [X] I agree to follow this project's Code of Conduct and Contribution Guidelines.

**Comment by gregsdennis** [comment]
Not sure this is a bug.  It's really just a feature that I hadn't considered.  Marked this as an enhancement.  Thanks for the idea and use case!

**Comment by 2BitSalute** [comment]
Is it OK if I submit a PR? It was a small change I could make in a Codespaces environment. I added a test :D
