### ISSUE TITLE
Generation/CodeGeneration integration with MSBuild tasks

### ISSUE THREAD

**Issue by 2BitSalute** [json-everything/json-everything#803]
### Documentation

- [X] I have consulted the [documentation](https://docs.json-everything.net), and my question isn't answered there.

### Nuget Package

JsonSchema.Net.Generation

### Package Version

4.5.1

### How can I help?  Please provide as much context as possible.

There are two parts to my question, and one probably belongs in the `Corvus.JsonSchema` rather than here, since [CodeGeneration has been deprecated](https://blog.json-everything.net/posts/dropping-codegen/).

## Part 1: Schema generation at build time
This is definitely pertinent to `JsonSchema.Net.Generation`.

What I want to do is generate a JSON schema as part of a project's build. The project may or may not be the one that contains the code that should be converted into the JSON schema.

This can be accomplished via an MSBuild task. Let's call it `GenerateJsonSchemaTask`.

I'm think this can be done either using the `RoslynCodeTaskFactory` approach or by writing a custom task, publishing it as a NuGet, then consuming it in a targets file/project files. An unfinished example of the second approach: https://github.com/JeffBarnard/JsonSchemaTask.NET

I will likely do this, but it feel like it could of general utility to have such a task.

What do you think?

## Part 2: Code generation from schema
This is the one I'm more unsure about.

Once I have my schema published in a NuGet package, the schema can be consumed by:
1) A schema validation MSBuild task in the project where JSON files are used that should conform to the published schema; let's call this one `JsonSchemaValidationTask`
2) A model generation MSBuild task in the project that does some code generation based on the types defined in the schema; let's call this one `ModelFromJsonSchemaTask`

(1) I think is fine and the solution could be similar to the approach in Part 1.

I'm not sure about (2), though. I don't *think* the Corvus tool can be used in an MSBuild task or as a package dependency for writing one. And `CodeGeneration` is deprecated and doesn't work with the latest versions of `JsonSchema.Net` packages (I tried, and got a `MissingMethodException` for something in `JsonSchemaExtensions`.

I'm thinking we could also write our own code generation code, which might be preferable, because we could emit types into separate files, add custom file headers, that kind of thing.

What do you think in general about these JsonSchema-related MSBuild task ideas?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
## Part 1

This sound like a great idea.  I don't have the time to dedicate to it, though.

I'd be interested to find out the difference in ease of implementation between what you're suggesting (MSBuild task) and perhaps a Roslyn source generator (if it even supports non-code files).

If you end up building it, package it and put it on Nuget!

## Part 2

I've tried code generation, and it didn't really work out well.  It did the job (kinda), but it wasn't robust.

I wrote a [blog post](https://blog.json-everything.net/posts/dropping-codegen/) about not supporting that library anymore, and I've marked the library as deprecated on Nuget.

The alternative you're looking for is going to be Corvus.JsonSchema.  @mwadams has done a good job with it, and the next version (in preview now) supports source generation.

We've been working together over the past month or so to integrate it into my Graeae project (OpenAPI).

**Comment by mwadams** [comment]
Let me know if you need a hand getting started with Corvus. I'm editing an intro video for the source generator as we speak.

**Comment by 2BitSalute** [comment]
Regarding part 2, yeah, that's what I got from reading the documentation and checking out `Corvus.JsonSchema`. Maybe I don't understand the tools well, but it doesn't seem like you could plug the source generation tool into a build task. Or could you?

Now that I think about it, I actually only tried the latest non-preview version. I should give it another look.

**Comment by gregsdennis** [comment]
It doesn't go into an MSBuild task, no.  Source generation happens as part of the code compilation.  You would:

1. install the nuget package, which adds the Roslyn analyzers
2. add any JSON files to your project as "additional files" ([example](https://github.com/gregsdennis/Graeae/blob/9e2e34b765b1115e0f156c840afb334fce65278e/Graeae.AspNet.Tests.Host/Graeae.AspNet.Tests.Host.csproj#L20-L22))

... and the compiler takes it from there.

**Comment by gregsdennis** [comment]
@2BitSalute did you make any progress here?
