### ISSUE TITLE
Json Logic does not apply on nested var

### ISSUE THREAD

**Issue by arjundg** [json-everything/json-everything#807]
### Nuget Package

json-everything.net (playground)

### Package Version

5.2.1

### Operating System

None

### .Net Target (if relevant, please specify the version in the description)

None

### A clear and concise description of the bug.

Following rule is returning null, even if JsonLogic javascript implementation is working fine:
Rule:
```json
{
    "*": [{
            "var": "amount"
        }, {
            "var": {
                "var": "target_currency"
            }
        }, {
            "/": ["1", {
                    "var": {
                        "var": "source_currency"
                    }
                }
            ]
        }
    ]
}
```
Data:
```json
{
    "amount": "100",
    "source_currency": "GBP",
    "target_currency": "EUR",
    "GBP": "1.1",
    "EUR": "0.8"
}
```
### What did you expect?

Output should be 72.72727272727272

### Please add test code or steps to reproduce the behavior.

var result = JsonLogic.Apply(rule, data);

### Code of Conduct & Contributor Guidelines

- [X] I agree to follow this project's Code of Conduct and Contribution Guidelines.

**Comment by gregsdennis** [comment]
Thanks for reporting this.  I'll have a look.

**Comment by gregsdennis** [comment]
Creating the Logic using the builder methods, I first found that having a nested variable wasn't supported, so I've added that.  Once that was added, running the test results in:

```
Expected: 72.72727272727272
Actual: 72.727272727272727272727272728
```

So it seems the rule itself is working.

I also set up a second test deserializing the Logic, and that works, but I wonder if this is where you're getting tripped.

Could you post exactly how you're taking the JSON for `rule` and passing it into `JsonLogic.Apply()`?

**Comment by gregsdennis** [comment]
@arjundg are you still needing this?

**Comment by arjundg** [comment]
Thanks a ton! I will test this out and hopefully this would work.
Apologies for the late reply.
