### ISSUE TITLE
JSON Schema validation fails for arrays with oneOf logic

### ISSUE THREAD

**Issue by AnakinRaW** [json-everything/json-everything#811]
### Nuget Package

JsonSchema.Net

### Package Version

7.2.3

### Operating System

Windows

### .Net Target (if relevant, please specify the version in the description)

.Net (5 or after)

### A clear and concise description of the bug.

Consider the following JSON Schema which shall represent an object which has an required list property. 

The list is designed in a way that, that it only supports items of a special type (in this case `obj`). Furthermore the array shall allow an optional first array element which is a enum value. The array shall never be empty.

```json
{
  "$id": "https://test/foo",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "$defs": {
    "obj": {
      "required": [
        "test"
      ]
    },
    "specialListWithOptionalStringPrexif": {
      "oneOf": [
        {
          "type": "array",
          "prefixItems": [
            {
              "enum": ["a", "b", "c"]
            }
          ],
          "items": {
            "type":"object",
            "$ref": "#/$defs/obj"
          }
        },
        {
          "type": "array",
          "items": {
            "type":"object",
            "$ref": "#/$defs/obj"
          }
        }
      ]
    }
  },
  "properties": {
    "name": {
      "type": "string"
    },
    "list": {
      "$ref": "#/$defs/specialListWithOptionalStringPrexif"
    }
  },
  "required": [
    "name",
    "list"
  ]
}
```

### What did you expect?

The following JSON should be valid but it is not
```json
{
  "name":"name",
  "list":["a", {"test":"a"}]
}
```

the report is: 
```json
 "valid": false,
"evaluationPath": "/properties/list/$ref/oneOf/1/items",
"schemaLocation": "https://test/foo#/$defs/specialListWithOptionalStringPrexif/oneOf/1/items",
"instanceLocation": "/list/0",
"errors": {
  "type": "Value is \"string\" but should be \"object\""
}
```

Also the following JSON should be valid but it is not
```json
{
  "name":"name",
  "list":[{"test":"a"}]
}
```

the report is: 
```json
"valid": false,
"evaluationPath": "/properties/list/$ref/oneOf/0/prefixItems/0",
"schemaLocation": "https://test/foo#/$defs/specialListWithOptionalStringPrexif/oneOf/0/prefixItems/0",
"instanceLocation": "/list/0",
"errors": {
  "enum": "Value should match one of the values specified by the enum"
}
```

### Please add test code or steps to reproduce the behavior.

The test cases on the playground: https://json-everything.net/json-schema do not work. 

I also conducted the following tests. While the negative tests pass the positive tests:

```cs
    public static IEnumerable<object[]> TestData()
    {
        yield return
        [
            @"{
  ""name"":""name"",
  ""list"":[{""test"":""1""}]
}", false
        ];

        yield return
        [
            @"{
  ""name"":""name"",
  ""list"":[{""test"":""1""}, {""test"":""2""}]
}", false
        ];

        yield return
        [
            @"{
  ""name"":""name"",
  ""list"":[""a"", {""test"":""1""}]
}", false
        ];

        yield return
        [
            @"{
  ""name"":""name"",
  ""list"":[""b"", {""test"":""1""}, {""test"":""2""}]
}", false
        ];

        // d is not a valid enum value
        yield return
        [
            @"{
  ""name"":""name"",
  ""list"":[""d"", {""test"":""value""}]
}", true
        ];

        // enum value must be the first value or not present
        yield return
        [
            @"{
  ""name"":""name"",
  ""list"":[{""test"":""value""}, ""a""]
}", true
        ];

        // Empty array is not allowed
        yield return
        [
            @"{
  ""name"":""name"",
  ""list"":[]
}", true
        ];

        // obj not satisfied
        yield return
        [
            @"{
  ""name"":""name"",
  ""list"":[""a"", {""non"":""value""}]
}", true
        ];
    }

    [Theory]
    [MemberData(nameof(TestData))]
    public void RunTests(string data, bool throws)
    {
        var node = JsonNode.Parse(data);
        var schema = JsonSchema.FromText(Schema);

        var result = schema.Evaluate(node, new EvaluationOptions { 
            EvaluateAs = SpecVersion.Draft202012, 
            OutputFormat = OutputFormat.Hierarchical});

        if (throws)
            Assert.Throws<EvaluateException>(() => ThrowOnValidationError(result));
        else
            ThrowOnValidationError(result);

        return;

        static void ThrowOnValidationError(EvaluationResults result)
        {
            if (result.HasErrors)
                throw new EvaluateException($"Error: {result.Errors!.First()}");
            foreach (var child in result.Details)
                ThrowOnValidationError(child);
        }
    }
```

### Is there any other information you'd like to share regarding this bug?

The test cases all work on https://www.jsonschemavalidator.net

### Code of Conduct & Contributor Guidelines

- [X] I agree to follow this project's Code of Conduct and Contribution Guidelines.

**Comment by gregsdennis** [comment]
> The following JSON should be valid but it is not
> 
> ```json
> {
>   "name":"name",
>   "list":["a", {"test":"a"}]
> }
> ```

> Also the following JSON should be valid but it is not
> 
> ```json
> {
>   "name":"name",
>   "list":[{"test":"a"}]
> }
> ```

Both of these instances are valid against the schema and both are reported as such.

The errors you're showing are reported from the subschema of the `oneOf` that failed.

This can be replicated quite simply:

```json
{
  "oneOf": [
    { "const": "a" },
    { "const": "b" },
  ]
}
```

The instance `"a"` will validate with `/oneOf/0`, but `/oneOf/1` will produce an error.  Similarly with the instance `"b"`.

The important thing is the overall validation result which is reported using the `valid` property at the root of the results.  For both instances, the root's `valid` property will be `true` _and_ a nested output unit will still show the error.

For more information on interpreting output, please read my [blog post](https://json-schema.org/blog/posts/interpreting-output) on the JSON Schema website.

**Comment by gregsdennis** [comment]
@AnakinRaW does the above answer your question?

**Comment by AnakinRaW** [comment]
Yes, thank you. I was not aware of the property `IsValid` and thus was confused with the meaning of `Errors`. Should have known better 🤦🏼‍♂️
