### ISSUE TITLE
Validate an OpenAPI spec against the OpenAPI 3.0 schema

### ISSUE THREAD

**Issue by bhaeussermann** [json-everything/json-everything#812]
### Documentation

- [X] I have consulted the [documentation](https://docs.json-everything.net), and my question isn't answered there.

### Nuget Package

JsonSchema.Net.OpenApi

### Package Version

3.1.0

### How can I help?  Please provide as much context as possible.

I need to validate an OpenAPI 3.0 specification against the OpenAPI 3.0 schema.

I'm trying to do this using the following code where the _OpenAPI-3.0-Schema.json_ file contains the [schema/2021-09-28](https://spec.openapis.org/oas/3.0/schema/2021-09-28.html) schema from the [OpenAPI Initiative Registry page](https://spec.openapis.org/)

```
var openApiSchema = JsonSchema.FromFile("OpenAPI-3.0-Schema.json");

using var definitionStream = File.OpenRead("MyDefinitionUsingOpenApi3.0.json");
var jsonNode = JsonNode.Parse(definitionStream);
var evaluationResults = openApiSchema.Evaluate(jsonNode);

if (!evaluationResults.IsValid)
{
    Console.WriteLine("Validation Failed!");
}
```

This fails to deserialize the schema in the `JsonSchema.FromFile()` call with the exception `System.Text.Json.JsonException: 'Expected number'`.

What am I missing?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
You actually need an additional package for this.  Go have a look at my Graeae project.  It has support for OpenAPI 3.0.

This project focuses on JSON Schema specifically and will only ever support draft 6 and later. OpenAPI 3.0 uses a modified draft 4.

**Comment by bhaeussermann** [comment]
@gregsdennis Thanks! I'm now using [Graeae](https://github.com/gregsdennis/Graeae) to validate the OpenAPI spec by simply trying to deserialize it like so:

```
using Graeae.Models;
using Yaml2JsonNode;

YamlSerializer.Deserialize<OpenApiDocument>(openApiDefinitionString);
```
