### ISSUE TITLE
Can't get simple netstandard2.0 app to work

### ISSUE THREAD

**Issue by sotteson1** [json-everything/json-everything#813]
### Documentation

- [X] I have consulted the [documentation](https://docs.json-everything.net), and my question isn't answered there.

### Nuget Package

JsonSchema.Net

### Package Version

7.2.3

### How can I help?  Please provide as much context as possible.

I'm trying to target netstandard2.0 so I can create a PowerShell module that works with both Windows PowerShell and PowerShell Core. I ran into trouble getting Windows PS to load my module, so then I tried creating a simple console app and it runs into the same problem:

````
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at System.MemoryExtensions.AsSpan(String text)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonTypeInfo`1 jsonTypeInfo)
   at TestJson3.Program.Main(String[] args) in C:\Users\sotteson\source\repos\TestJson3\Program.cs:line 13
````

My .csproj:
````csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>8.0</LangVersion>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JsonSchema.Net" Version="7.2.3" />
  </ItemGroup>

</Project>
````

C# code:
````C#
var schemaText = File.ReadAllText(@"D:\scratch\test.schema.json");
var schema = JsonSchema.FromText(schemaText);
````

It looks like System.Text.Json uses System.Threading.Tasks.Extensions which uses System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1. But System.Text.Json itself depends on System.Runtime.CompilerServices.Unsafe, Version=6.0.0.0.

Is there any way around this? It seems like this is the simplest case for using JsonSchema.Net in a netstandard2.0, so maybe I'm missing something dumb.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sotteson1** [comment]
I found a hacky way to get around this. I don't think this method is documented, but I used ProcMon to see how netstandard2.0 was probing for the DLL. I had to add this to the output directory:
System.Runtime.CompilerServices.Unsafe\System.Runtime.CompilerServices.Unsafe.dll (with the version it's looking for)

And then I had to do this again for System.Buffers for 4.0.2:
System.Buffers\System.Buffers.dll

**Comment by gregsdennis** [comment]
This seems to do with the performance improvements I made some time ago.  I'm not sure what to do here.

**Comment by gregsdennis** [comment]
```xml
    <OutputType>Exe</OutputType>
    <TargetFramework>netstandard2.0</TargetFramework>
```
I think the problem is here.  You can't build an app on .Net Standard.  You have to use modern .Net (e.g. net8.0 / net9.0) or .Net Framework (net481).
