### ISSUE TITLE
OpenAPI <--> JsonSchema 

### ISSUE THREAD

**Issue by ansible42** [json-everything/json-everything#816]
### Documentation

- [X] I have consulted the [documentation](https://docs.json-everything.net), and my question isn't answered there.

### Nuget Package

JsonSchema.Net.OpenApi

### Package Version

8.0.10

### How can I help?  Please provide as much context as possible.

Trying to use the `JsonSchema` that we can update and check payloads against, but we need to generate `IDictionary<string, OpenApiMediaType>` for defining our examples. 

Not sure if I am just not seeing it. 

Thanks,

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
I have a separate project that completes the OpenAPI story:  Graeae.
