### ISSUE TITLE
expression fails if condition contains new line char

### ISSUE THREAD

**Issue by sean-wickstrom** [json-everything/json-everything#819]
### Nuget Package

JsonPath.Net

### Package Version

1.1.6

### Operating System

Windows

### .Net Target (if relevant, please specify the version in the description)

.Net (5 or after)

### A clear and concise description of the bug.

if the condition value contains a new line character
  Json.Path.JsonPath.Parse("$[?(@.row == 'a\nb')]")
the following exception is thrown
Json.Path.PathParseException: Pattern '?(@.row ==...' not recognized

### What did you expect?

the expressed to be parsed and be able to be used in to call the EvalutePath method

### Please add test code or steps to reproduce the behavior.

  Json.Path.JsonPath.Parse("$[?(@.row == 'a\nb')]")

### Code of Conduct & Contributor Guidelines

- [X] I agree to follow this project's Code of Conduct and Contribution Guidelines.

**Comment by gregsdennis** [comment]
> `Json.Path.JsonPath.Parse("$[?(@.row == 'a\nb')]")`

In this case, the `\n` is actually a new line in the C# string.  I suspect you want it to be part of the JSON Path expression string.  If that's the case, you need to double-escape it.

```
Json.Path.JsonPath.Parse("$[?(@.row == 'a\\nb')]")
```

**Comment by gregsdennis** [comment]
@sean-wickstrom does this resolve your issue?
