### ISSUE TITLE
How to make NodeListFunctionDefinition work?

### ISSUE THREAD

**Issue by FranklyDev** [json-everything/json-everything#821]
### Documentation

- [X] I have consulted the [documentation](https://docs.json-everything.net), and my question isn't answered there.

### Nuget Package

JsonPath.Net

### Package Version

1.1.6

### How can I help?  Please provide as much context as possible.

I'm trying to extend the existing functions with a function of type NodeType, but cannot figure out how to make it work. I'm unsure if it's a bug or has not yet been implemented, as it seems that only the logical functions are referring back to the FunctionRepository, and as the NodeListFunctionDefinition isn't a logical one, that fails to parse the path.

Here's the definition I'm trying to use (minimalistic implementation):

```
 public class MagicFunction : NodelistFunctionDefinition
    {
        public override string Name => "magic";

        public NodeList? Evaluate(NodeList? nodeList)
        {
            return nodeList;
        }
    }
```

I registered it via `FunctionRepository.RegisterNodelistFunction<MagicFunction>();` which seems to work fine.

Then I try to parse a JsonPath, which fails. I haven't found other examples for NodeType functions anywhere else, so maybe the path is wrong?

```
const string jsonPath = "$.foo[?magic(@)].bar";
var path = JsonPath.Parse(jsonPath); // throws an Exception
```

I'm trying something pretty special and a valid answer to my question might also be that I'm going at it all wrong :) So here's what I'm trying to do: For the path above, I would like my new nodelist function to take the matches up to that part (so `.foo`) and then return a fresh JSON (from outside) that will include the `.bar`. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
No, this is definitely a bug.

I am interested in your use case, however.  When writing the spec, we couldn't think of any useful functions that would return a nodelist.

**Comment by FranklyDev** [comment]
> No, this is definitely a bug.

Any idea how hard it is to fix and if it will be available in the next version?

> I am interested in your use case, however. When writing the spec, we couldn't think of any useful functions that would return a nodelist.

I'm under a NDA, so can't reveal details. However, the general use case is rather straightforward (albeit it may not be the intended way to use JsonPath, hence my question 🤷‍♂️) : we have a distributed set of JSON documents that link to each other in certain places and so we want to navigate through them almost as if it was a single document. Fetching them all and combining them though would be very expensive, so the idea was to use a function expression in the path to fetch only the relevant parts. It would allow seamless traversal across distributed documents, but of course have some limitations (which we are fine with), like the `**` behaviour not extending beyond the current's document scope.

**Comment by gregsdennis** [comment]
I got this working, and I think I'm going to propose this gets added to the test suite.

The missing piece was that a nodelist function could operate as any nodelist would, so you can put it in a place in the expression where a logical type would be expected and it will act as an existence test.

So if we define the `noop()` function to take a nodelist and return the same nodelist, then `$[?@.*]`, which returns nodes that have children, will operate identically to `$[?noop(@.*)]`.

I'll be including this with an upcoming update to support .net 9 in all the libs.
