### ISSUE TITLE
Published nuget package dependencies missing!

### ISSUE THREAD

**Issue by Havunen** [json-everything/json-everything#823]
### Nuget Package

json-everything.net (playground)

### Package Version

JsonSchema.Net.Generation

### Operating System

None

### .Net Target (if relevant, please specify the version in the description)

None

### A clear and concise description of the bug.

JsonSchema.Net.Generation v4.6.0 released to Nuget depends on https://www.nuget.org/packages/JsonSchema.Net v7.3.0 which is not available in nuget!

### What did you expect?

nuget install works

### Please add test code or steps to reproduce the behavior.

install JsonSchema.Net.Generation 4.6.0

### Code of Conduct & Contributor Guidelines

- [X] I agree to follow this project's Code of Conduct and Contribution Guidelines.

**Comment by gregsdennis** [comment]
Ugh. Thanks for letting me know. I updated everything, and it seems this one fell through the cracks.  It's late here, and I'm about to go to bed. I can check tomorrow.

**Comment by gregsdennis** [comment]
Looks like I had forgotten that I disabled the build while I try to work out package signing.  I've run it, and it should publish shortly.
