### ISSUE TITLE
Fail to parse valid jsonpath

### ISSUE THREAD

**Issue by isaevdan** [json-everything/json-everything#824]
### Nuget Package

JsonPath.Net

### Package Version

2.0.0

### Operating System

None

### .Net Target (if relevant, please specify the version in the description)

None

### A clear and concise description of the bug.

'#' character is not accepted in jsonpath, while it is still valid character for json key string

### What did you expect?

'#' and other characters should be accepted in jsonpath string

### Please add test code or steps to reproduce the behavior.

```
var json = "{ "#text" : 123 }";
var path = "$.#text";
var jsonPath = JsonPath.Parse(path);
```

### Is there any other information you'd like to share regarding this bug?

Checked it on this [site](https://jsonpath.com/) and it works. 
[SO question](https://stackoverflow.com/questions/8676011/which-characters-are-valid-invalid-in-a-json-key-name) related to valid characters.

Code in library to update:
UtilityExtensions.IsValidForPropertyName
UtilityExtensions.IsValidForPropertyNameStart

### Code of Conduct & Contributor Guidelines

- [X] I agree to follow this project's Code of Conduct and Contribution Guidelines.

**Comment by gregsdennis** [comment]
> '#' and other characters should be accepted in jsonpath string

Per RFC 9535, the only characters allowable in the shorthand property name syntax are alphanumeric and underscore.  To select a property with`#`, you must use the bracket syntax. 

```jsonpath
$['#text']
```

**Comment by isaevdan** [comment]
Got you, stackoverflow missguided. Thanks for help!
