### ISSUE TITLE
[JsonPatch]: Move with "-" index is not working

### ISSUE THREAD

**Issue by vimateck** [json-everything/json-everything#825]
### Nuget Package

JsonPatch.Net

### Package Version

3.2.0

### Operating System

Windows

### .Net Target (if relevant, please specify the version in the description)

.Net (5 or after)

### A clear and concise description of the bug.

When using the "-" operator in a json pointer for an array object, I want to have the "from" value added at the end of the "path" array.

This is also described here: https://datatracker.ietf.org/doc/html/rfc6902#appendix-A.16

### What did you expect?

Value added to the end of the array.

### Please add test code or steps to reproduce the behavior.

```csharp
    [TestMethod]
    public void MoveShouldMoveItemAround()
    {
        // Arrange
        var model = new { Items = new[] { 1, 2, 3, 4, 5 } };
        var jsonModel = JsonSerializer.SerializeToNode(model);

        var doc = new global::Json.Patch.JsonPatch(
            PatchOperation.Move(
                JsonPointer.Parse("/Items/2"),
                JsonPointer.Parse("/Items/-")));

        // Act
        var result = doc.Apply(jsonModel);

        // Assert
        result.Error.Should().BeEmpty();
        result.Result!["Items"]!.AsArray()[^1].Should().BeEquivalentTo(3);
    }
```

returns: `Expected result.Error to be empty, but found "Target path `/Items/-` could not be reached.".`

### Is there any other information you'd like to share regarding this bug?

Looking into the implementation, this line should be the cause of this bug:

```
		[...]
			if (lastPathSegment.Length == 0 && lastPathSegment[0] == '-')
				index = arrTarget.Count;
		[...]
```

https://github.com/json-everything/json-everything/blob/cf4faf3928287a5eacd611df3dec3ffea70edb3c/src/JsonPatch/MoveOperationHandler.cs#L64

This is always false, because if the length is null, it can never also be '-'.

### Code of Conduct & Contributor Guidelines

- [X] I agree to follow this project's Code of Conduct and Contribution Guidelines.

Edit: a similar issue should also occur in copy:
https://github.com/json-everything/json-everything/blob/cf4faf3928287a5eacd611df3dec3ffea70edb3c/src/JsonPatch/CopyOperationHandler.cs#L44

**Comment by gregsdennis** [comment]
Yeah, looks like I have flipped logic in my equality.  Happens occasionally. 😆

**Comment by vimateck** [comment]
Thanks for the quick fixes.

I had just mentioned it in an edit, but the same issue also occurs for the copy operation:
https://github.com/json-everything/json-everything/blob/31afd0e387a187816c26c67eb7cb77227ef9d1df/src/JsonPatch/CopyOperationHandler.cs#L44

**Comment by gregsdennis** [comment]
Dangit. Missed that.  If you want to set up a PR, I'd be happy to merge it.  Please bump the patch version and add a release note.
