### ISSUE TITLE
[JsonPatch]: Copy into an array does not work as specified

### ISSUE THREAD

**Issue by vimateck** [json-everything/json-everything#826]
### Nuget Package

JsonPatch.Net

### Package Version

3.2.0

### Operating System

Windows

### .Net Target (if relevant, please specify the version in the description)

.Net (5 or after)

### A clear and concise description of the bug.

The specification of JsonPatch tells:
` This operation [copy] is functionally identical to an "add" operation at the
   target location using the value specified in the "from" member.` --> https://datatracker.ietf.org/doc/html/rfc6902#section-4.5

This does currently not work, as the implementation will always override the index position and will not insert a new item at the position (as add is doing it).

### What did you expect?

Copying a value into an array with specified index is inserting the value at this index.

### Please add test code or steps to reproduce the behavior.

```csharp
    [TestMethod]
    public void CopyShouldCopyValuesToTarget()
    {
        // Arrange
        var model = new { Items = new[] { 1, 2, 3, 4, 5 } };
        var jsonModel = JsonSerializer.SerializeToNode(model);

        // Act 1
        var addDoc = new global::Json.Patch.JsonPatch(
            PatchOperation.Add(
                JsonPointer.Parse("/Items/0"),
                JsonNode.Parse("3")));

        var addResult = addDoc.Apply(jsonModel);

        // Assert 1
        addResult.Error.Should().BeNullOrEmpty();
        addResult.Result!["Items"]!.ToJsonString().Should().Be("[3,1,2,3,4,5]");

        // Act 2
        var copyDoc = new global::Json.Patch.JsonPatch(
            PatchOperation.Copy(
                JsonPointer.Parse("/Items/2"),
                JsonPointer.Parse("/Items/0")));

        var copyResult = copyDoc.Apply(jsonModel);

        // Assert 2
        copyResult.Error.Should().BeNullOrEmpty();
        copyResult.Result!["Items"]!.ToJsonString().Should().Be("[3,1,2,3,4,5]");
    }
```

Output: `Expected copyResult.Result!["Items"]!.ToJsonString() to be "[3,1,2,3,4,5]" with a length of 13, but "[3,2,3,4,5]" has a length of 11, differs near "2,...`

### Is there any other information you'd like to share regarding this bug?

This place in code will always update the index, but will not insert a new item at this position:
https://github.com/json-everything/json-everything/blob/cf4faf3928287a5eacd611df3dec3ffea70edb3c/src/JsonPatch/CopyOperationHandler.cs#L50

### Code of Conduct & Contributor Guidelines

- [X] I agree to follow this project's Code of Conduct and Contribution Guidelines.

**Comment by gregsdennis** [comment]
Yep.  Thanks for the report and identification.
