### ISSUE TITLE
7.3.0 causes a warning (and an error) in Framework projects

### ISSUE THREAD

**Issue by na1307** [json-everything/json-everything#844]
### Nuget Package

JsonSchema.Net

### Package Version

7.3.0

### Operating System

Windows

### .Net Target (if relevant, please specify the version in the description)

.Net Framework

### A clear and concise description of the bug.

Using 7.3.0 in .NET Framework projects will result in a MSB3277 warning. It does not occur in .NET (Core) projects. In some projects, a CS1705 error may appear (I don't know why).

### What did you expect?

There should be no errors or warnings.

### Please add test code or steps to reproduce the behavior.

A Project that cause MSB3277 warning: https://github.com/na1307/test/tree/main/JsonTest/JsonTest

A Project that also cause CS1705 error: https://github.com/na1307/SimpleSixtarScorecard/tree/dependabot_nuget_default-3132ca9f24/SimpleSixtarScorecard

### Is there any other information you'd like to share regarding this bug?

The warning is as follows:

```
C:\Program Files\dotnet\sdk\9.0.101\Microsoft.Common.CurrentVersion.targets(2413,5): warning MSB3277:
      Found conflicts between different versions of "System.Text.Json" that could not be resolved.
      There was a conflict between "System.Text.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" and "System.Text.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51".
          "System.Text.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" was chosen because it was primary and "System.Text.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" was not.
          References which depend on "System.Text.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" [D:\nugetcache\system.text.json\8.0.0\lib\net462\System.Text.Json.dll].
              D:\nugetcache\system.text.json\8.0.0\lib\net462\System.Text.Json.dll
                Project file item includes which caused reference "D:\nugetcache\system.text.json\8.0.0\lib\net462\System.Text.Json.dll".
                  D:\nugetcache\system.text.json\8.0.0\lib\net462\System.Text.Json.dll
          References which depend on or have been unified to "System.Text.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" [].
              D:\nugetcache\json.more.net\2.0.1.2\lib\netstandard2.0\Json.More.dll
                Project file item includes which caused reference "D:\nugetcache\json.more.net\2.0.1.2\lib\netstandard2.0\Json.More.dll".
                  D:\nugetcache\json.more.net\2.0.1.2\lib\netstandard2.0\Json.More.dll
                  D:\nugetcache\jsonpointer.net\5.0.0\lib\netstandard2.0\JsonPointer.Net.dll
                  D:\nugetcache\jsonschema.net\7.3.0\lib\netstandard2.0\JsonSchema.Net.dll
              D:\nugetcache\jsonpointer.net\5.0.0\lib\netstandard2.0\JsonPointer.Net.dll
                Project file item includes which caused reference "D:\nugetcache\jsonpointer.net\5.0.0\lib\netstandard2.0\JsonPointer.Net.dll".
                  D:\nugetcache\jsonpointer.net\5.0.0\lib\netstandard2.0\JsonPointer.Net.dll
                  D:\nugetcache\jsonschema.net\7.3.0\lib\netstandard2.0\JsonSchema.Net.dll
              D:\nugetcache\jsonschema.net\7.3.0\lib\netstandard2.0\JsonSchema.Net.dll
                Project file item includes which caused reference "D:\nugetcache\jsonschema.net\7.3.0\lib\netstandard2.0\JsonSchema.Net.dll".
                  D:\nugetcache\jsonschema.net\7.3.0\lib\netstandard2.0\JsonSchema.Net.dll
```

I'm using SDK 9.0 here, but it seems to appear regardless of SDK version.

The error can be found at [this link](https://github.com/na1307/SimpleSixtarScorecard/actions/runs/12516359872/job/34915330289).

### Code of Conduct & Contributor Guidelines

- [X] I agree to follow this project's Code of Conduct and Contribution Guidelines.

**Comment by gregsdennis** [comment]
Please make sure that you're referencing the System.Text.Json v9 library.

I never directly supported .Net Framework in any of these libraries.  I build to .Net Standard, so most of the time it _should_ work, but I never tested it.  With the update to .Net 9, I did try to add .Net Framework to the test projects, but was having trouble getting it to build and gave up.

Functionally, there's nothing different in the latest version, so I'd advise to stay on the previous version until you can update your applications to use the latest .Net.

**Comment by na1307** [comment]
When I upgraded Json.More.Net to 2.1.0, the warning disappeared. I think the reason is that JsonSchema.csproj directly references the latest version of the project, but nuspec still references the older version.

**Comment by gregsdennis** [comment]
Ah, yes. I've seen this before. I need to figure out how to include a check in the build.

I'll push out an update.
