### ISSUE TITLE
Type 'ErrorMessages' should not be public

### ISSUE THREAD

**Issue by cptjazz** [json-everything/json-everything#846]
### Nuget Package

JsonSchema.Net

### Package Version

7.3.0

### Can this library make doing something simpler?

Reducing the public surface in general allows for easier integration of later optimizations/refactorings/...
The type is clearly an implementation detail and should never have been public.

Yes, technically this is a breaking change in the ABI, but I would argument my way out here that there are no valid use cases for a dependee of this library to use internal error texts.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
`ErrorMessages` is very intentionally public to allow people to customize error messages to their needs. This is a significant feature of the library. Please see the docs.

https://docs.json-everything.net/schema/basics/#schema-errors

**Comment by cptjazz** [comment]
I see; obviously I didn't read the documentation thoroughly enough 😅 

Let me propose then to internalize the methods `GetXxx(CultureInfo? culture)` and `ReplaceToken(..)` and keep only the message string properties public.
This allows for setting the error messages from extern, but hides the internal wiring.

**Comment by gregsdennis** [comment]
Nope.  People need to be able to access this to create their own keywords.  It all needs to be public. 

My default when adding anything is to make it internal. Then I have a think and make it public if it needs to be. 

These need to be public.
